[package]
name = "question-rust-inlining"
version = "0.1.0"
authors = ["Kevin J. Lynagh <kevin@keminglabs.com>"]
edition = "2018"

[dependencies]
rand = "0.6"
lazy_static = "1.2.0"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "match_vs_lookup"
harness = false
